---
on:
  workflow_call:
    outputs:
      changed-files:
        description: "Changed file JSON output from dorny/paths-filter"
        value: ${{ jobs.get-changed-files.outputs.changed-files }}

jobs:
  get-changed-files:
    name: Get Changed Files
    runs-on: ubuntu-24.04
    permissions:
      contents: read  # for dorny/paths-filter to fetch a list of changed files
      pull-requests: read  # for dorny/paths-filter to read pull requests
    outputs:
      changed-files: ${{ toJSON(steps.changed-files.outputs) }}

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Get Changed Files
        id: changed-files
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36  # v3.0.2
        with:
          token: ${{ github.token }}
          list-files: escape
          filters: |
            repo:
              - added|modified:
                - '**'
            deleted:
              - deleted:
                - '**'
            pre-commit:
              - added|modified|deleted:
                - .pre-commit-config.y?(a)ml
                - .pylintrc
            docs:
              - added|modified|deleted:
                - .github/**
                - changelog/**
                - docs/**
                - noxfile.py
                - CHANGELOG.md
                - pyproject.toml
            needs_tests:
              - added|modified|deleted:
                - .github/**
                - data/**
                - jinja_extensions/**
                - project/**
                - tasks/**
                - tests/**
                - copier.yml
                - noxfile.py
                - pyproject.toml
                - pytest.ini

      - name: Echo Changed Files Output
        run: echo "${{ toJSON(steps.changed-files.outputs) }}"
